# Generated by Django 3.0.2 on 2020-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_following_+', to='accounts.UserProfile'),
        ),
    ]
